## code to prepare `brasil_soccer_league` dataset goes here
d<-readr::read_csv('./data-raw/brazil_soccer_league_full.csv')
brasil_soccer_league <-d %>%
  dplyr::rename('Time'='Horário',
                'WeekDay'='Dia',
                'Date'='Data',
                'HomeTeam'='Clube 1',
                'VisitorTeam'='Clube 2',
                'Stadium'='Arena',
                'ScoreHomeTeam'='Clube 1 Gols',
                'ScoreVisitorTeam'='Clube 2 Gols',
                'Round'='Rodada') %>%
  dplyr::select(-Vencedor, -'Clube 1 Estado', -'Clube 2 Estado', -'Estado Clube Vencedor') %>%
  dplyr::filter(Date >= as.Date("2017-01-01") & Date <= as.Date("2019-12-31")) %>%
  dplyr::mutate(Round=case_when(Round=="1ª Rodada"~ 1,
                                Round=="2ª Rodada"~ 2,
                                Round=="3ª Rodada"~ 3,
                                Round=="4ª Rodada"~ 4,
                                Round=="5ª Rodada"~ 5,
                                Round=="6ª Rodada"~ 6,
                                Round=="7ª Rodada"~ 7,
                                Round=="8ª Rodada"~ 8,
                                Round=="9ª Rodada"~ 9,
                                Round=="10ª Rodada"~ 10,
                                Round=="11ª Rodada"~ 11,
                                Round=="12ª Rodada"~ 12,
                                Round=="13ª Rodada"~ 13,
                                Round=="14ª Rodada"~ 14,
                                Round=="15ª Rodada"~ 15,
                                Round=="16ª Rodada"~ 16,
                                Round=="17ª Rodada"~ 17,
                                Round=="18ª Rodada"~ 18,
                                Round=="19ª Rodada"~ 19,
                                Round=="20ª Rodada"~ 20,
                                Round=="21ª Rodada"~ 21,
                                Round=="22ª Rodada"~ 22,
                                Round=="23ª Rodada"~ 23,
                                Round=="24ª Rodada"~ 24,
                                Round=="25ª Rodada"~ 25,
                                Round=="26ª Rodada"~ 26,
                                Round=="27ª Rodada"~ 27,
                                Round=="28ª Rodada"~ 28,
                                Round=="29ª Rodada"~ 29,
                                Round=="30ª Rodada"~ 30,
                                Round=="31ª Rodada"~ 31,
                                Round=="32ª Rodada"~ 32,
                                Round=="33ª Rodada"~ 33,
                                Round=="34ª Rodada"~ 34,
                                Round=="35ª Rodada"~ 35,
                                Round=="36ª Rodada"~ 36,
                                Round=="37ª Rodada"~ 37,
                                Round=="38ª Rodada"~ 38)) %>%
  dplyr::mutate(WeekDay=case_when(WeekDay=="Segunda-feira"~ 'Monday',
                                  WeekDay=="Terça-feira"~ 'Tuesday',
                                  WeekDay=="Quarta-feira"~ 'Wednesday',
                                  WeekDay=="Quinta-feira"~ 'Thursday',
                                  WeekDay=="Sexta-feira"~ 'Friday',
                                  WeekDay=="Sábado"~ 'Saturday',
                                  WeekDay=="Domingo"~ 'Sunday'))
usethis::use_data(brasil_soccer_league, overwrite = TRUE)
