## code to prepare `tennis_agresti` dataset goes here
tennis_agresti <- tibble::tribble(~player0, ~player1, ~wins_player0, ~wins_player1,
                                     'Seles', 'Graf', 2, 3,
                                     'Seles', 'Sabatini', 1, 0,
                                     'Seles', 'Navratilova', 3, 3,
                                     'Seles', 'Sanchez', 2, 0,
                                     'Graf', 'Sabatini', 6, 3,
                                     'Graf', 'Navratilova', 3, 0,
                                     'Graf', 'Sanchez', 7, 1,
                                     'Sabatini', 'Navratilova', 1, 2,
                                     'Sabatini', 'Sanchez', 3, 2,
                                     'Navratilova', 'Sanchez',3, 1
)

tennis_agresti_2 <- tibble::tribble(~player0, ~player1, ~y, ~id,
                                  'Seles', 'Graf', 0, 1,
                                  'Seles', 'Graf', 0, 2,
                                  'Seles', 'Graf', 1, 3,
                                  'Seles', 'Graf', 1, 4,
                                  'Seles', 'Graf', 1, 5,
                                  'Seles', 'Sabatini', 0, 6,
                                  'Seles', 'Navratilova', 0, 7,
                                  'Seles', 'Navratilova', 0, 8,
                                  'Seles', 'Navratilova', 0, 9,
                                  'Seles', 'Navratilova', 1, 10,
                                  'Seles', 'Navratilova', 1, 11,
                                  'Seles', 'Navratilova', 1, 12,
                                  'Seles', 'Sanchez', 0, 13,
                                  'Seles', 'Sanchez', 0, 14,
                                  'Graf', 'Sabatini', 0, 15,
                                  'Graf', 'Sabatini', 0, 16,
                                  'Graf', 'Sabatini', 0, 17,
                                  'Graf', 'Sabatini', 0, 18,
                                  'Graf', 'Sabatini', 0, 19,
                                  'Graf', 'Sabatini', 0, 20,
                                  'Graf', 'Sabatini', 1, 21,
                                  'Graf', 'Sabatini', 1, 22,
                                  'Graf', 'Sabatini', 1, 23,
                                  'Graf', 'Navratilova', 0, 24,
                                  'Graf', 'Navratilova', 0, 25,
                                  'Graf', 'Navratilova', 0, 26,
                                  'Graf', 'Sanchez', 0, 27,
                                  'Graf', 'Sanchez', 0, 28,
                                  'Graf', 'Sanchez', 0, 29,
                                  'Graf', 'Sanchez', 0, 30,
                                  'Graf', 'Sanchez', 0, 31,
                                  'Graf', 'Sanchez', 0, 32,
                                  'Graf', 'Sanchez', 0, 33,
                                  'Graf', 'Sanchez', 1, 34,
                                  'Sabatini', 'Navratilova', 0, 35,
                                  'Sabatini', 'Navratilova', 1, 36,
                                  'Sabatini', 'Navratilova', 1, 37,
                                  'Sabatini', 'Sanchez', 0, 38,
                                  'Sabatini', 'Sanchez', 0, 39,
                                  'Sabatini', 'Sanchez', 0, 40,
                                  'Sabatini', 'Sanchez', 1, 41,
                                  'Sabatini', 'Sanchez', 1, 42,
                                  'Navratilova', 'Sanchez',0, 43,
                                  'Navratilova', 'Sanchez',0, 44,
                                  'Navratilova', 'Sanchez',0, 45,
                                  'Navratilova', 'Sanchez',1, 46
)

usethis::use_data(tennis_agresti, overwrite = TRUE)
usethis::use_data(tennis_agresti_2, overwrite = TRUE)
