---
title: "e_contributing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{e_contributing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Contributing

If you are interested you are welcome to contribute to the repository through pull requests.

If you have a strong need for a model that is not covered in this package (and do not want to code it yourself) send me an email or a suggestion in Github

## Short guide/suggestions

The points below are mostly reminders for me but hopefully it can help others

* Use the `devtools` package to create R files, test files, vignettes etc
* In the R folder:
  - `bpc.R`: this contains a single function (rather large) that is the main function call of the package. Each new model should be added here in the if else section with the appropriated data list for stan. Don't forget to add the relevant documentation in roxygen2
  - `bpc_exports.R`: these are helper functions to handle the `bpc` object and are exposed to the user. Only add here functions that receive a bpc object and that the users will have an interest. 
  - `bpc_get_probabilities.R` Since this is a big export function we have moved it to its own file
  - `bpc_helpers_X.R` additional functions to facilitate and support either the bpc function or the exports functions. None of these functions should be exported, although all of them should be documented. We divided these helpers in several files. the indexes are related to creating and checking names and indexes in lookup tables, the hpd to HPDI related functions, the checks to check correct specification of the data frame columns
  - `bpc_s3.R` all functions here are the custom implementation of the generic base functions from R, such as `summary`, `print`, `predict`
  - `data-docs.R` documentation for the data.
  - `bpc_object.R` declaration and creation of the bpc class.
* To add new models:
  1. Add the stan file with the model in inst/stan.
    - Note that we add two stan files for each model, one that will estimate the parameters and one that will make predictions
  3. add the appropriated hooks in the `bpc` function in `bpc.R` so we can call the model
  4. add the appropriated hooks in the `predict` function in `bpc_s3.R`.
  5. add the appropriated hooks for the `get_probabilities` function in `bpc_get_probabilities.R`  to generate the appropriated probability table that is called in the `summary` function.
  6. add the relevant tests to each of the modifications (to be improved with time, since we have very few tests now)
* Problems with `rstantools` and compiling the models. For me at least, the combination of `RStudio`+ `rstantools` + `roxygen2` + `devtools` + `Rcpp`+ `devtools` gives an assorted amount of stochastic errors can usually be solved with a combination of the actions below. For me it is still trial and error to fix the error but it usually works with these actions:
  - Restart the r session and try `devtools::load_all()` again
  - After adding a model try `devtools::document()`
  - If deleting a model file delete the appropriated line in stanmodels.R and do document again
  - If the model is not recompiling or updating do `pkgbuild::clean_dll()` then `devtools::document()` and possibly `devtools::load_all()` or `devtools::install()`

There are some dev-functions in inst/devfunctions to help building the package website and running test coverage (and submitting to codecov).
