// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4bt_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btU_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btUpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btgeneralized_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btgeneralizedpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btordereffect_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btordereffectpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4btpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidson_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsonU_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsonUpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsongeneralized_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsongeneralizedpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsonordereffect_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsonordereffectpredict_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4davidsonpredict_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4bt_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4bt_mod, 0},
    {"_rcpp_module_boot_stan_fit4btU_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btU_mod, 0},
    {"_rcpp_module_boot_stan_fit4btUpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btUpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4btgeneralized_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btgeneralized_mod, 0},
    {"_rcpp_module_boot_stan_fit4btgeneralizedpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btgeneralizedpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4btordereffect_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btordereffect_mod, 0},
    {"_rcpp_module_boot_stan_fit4btordereffectpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btordereffectpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4btpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4btpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidson_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidson_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsonU_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsonU_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsonUpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsonUpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsongeneralized_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsongeneralized_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsongeneralizedpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsongeneralizedpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsonordereffect_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsonordereffect_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsonordereffectpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsonordereffectpredict_mod, 0},
    {"_rcpp_module_boot_stan_fit4davidsonpredict_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4davidsonpredict_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bpcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
