# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("bt", "btU", "btUpredict", "btgeneralized", "btgeneralizedpredict", "btordereffect", "btordereffectpredict", "btpredict", "davidson", "davidsonU", "davidsonUpredict", "davidsongeneralized", "davidsongeneralizedpredict", "davidsonordereffect", "davidsonordereffectpredict", "davidsonpredict")

# load each stan module
Rcpp::loadModule("stan_fit4bt_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btU_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btUpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btgeneralized_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btgeneralizedpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btordereffect_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btordereffectpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4btpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsonU_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsonUpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsongeneralized_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsongeneralizedpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsonordereffect_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsonordereffectpredict_mod", what = TRUE)
Rcpp::loadModule("stan_fit4davidsonpredict_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
